In [1]:
import pandas as pd
from pandas  import ExcelWriter

# Reading the vehicle Trade csv file

In [2]:
csvv_df = pd.read_csv("vehicle_trade_data.csv")

In [3]:
csvv_df

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
0,202010014440649,31534.0,17,Grey,MINI,Hatch,USED,2017.0,19000,Hatchback,False,Petrol,MINI - Hatch,5
1,202010155026725,52023.0,66,Blue,Volkswagen,Golf,USED,2016.0,13500,Estate,False,Diesel,Volkswagen - Golf,6
2,202008142485309,29500.0,12,Grey,Mercedes-Benz,C Class,USED,2012.0,9495,Saloon,False,Petrol,Mercedes-Benz - C Class,10
3,202009183894045,35300.0,18,Grey,Vauxhall,Corsa,USED,2018.0,7293,Hatchback,False,Petrol,Vauxhall - Corsa,4
4,202010014441671,47299.0,65,Black,Nissan,Qashqai,USED,2016.0,11500,SUV,False,Diesel,Nissan - Qashqai,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96264,202010295556637,28225.0,17,White,Mercedes-Benz,C Class,USED,2017.0,18499,Saloon,False,Diesel,Mercedes-Benz - C Class,5
96265,202010305614799,122000.0,07,Silver,BMW,3 Series,USED,2007.0,1990,Saloon,False,Petrol,BMW - 3 Series,15
96266,202010315639231,45000.0,15,Silver,Vauxhall,Corsa,USED,2015.0,5000,Hatchback,False,Petrol,Vauxhall - Corsa,7
96267,202010315647416,4075.0,69,Grey,Nissan,Juke,USED,2019.0,18000,SUV,False,Petrol,Nissan - Juke,3
96268,202010315659271,52760.0,62,White,Nissan,Qashqai,USED,2012.0,7250,SUV,False,Petrol,Nissan - Qashqai,10

# Filter standard make with respect to car Brands

In [4]:
a=csvv_df[csvv_df["standard_make"]=="Mercedes-Benz"]
a

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
2,202008142485309,29500.0,12,Grey,Mercedes-Benz,C Class,USED,2012.0,9495,Saloon,False,Petrol,Mercedes-Benz - C Class,10
15,202008252922747,54000.0,15,White,Mercedes-Benz,E Class,USED,2015.0,13450,Saloon,False,Diesel,Mercedes-Benz - E Class,7
18,202008313128882,29062.0,66,Grey,Mercedes-Benz,A Class,USED,2016.0,15877,Hatchback,False,Petrol,Mercedes-Benz - A Class,6
27,202009173839578,20729.0,17,Silver,Mercedes-Benz,A Class,USED,2017.0,14685,Hatchback,False,Diesel,Mercedes-Benz - A Class,5
33,202009244147952,28411.0,19,Black,Mercedes-Benz,E Class,USED,2019.0,26455,Saloon,False,Diesel,Mercedes-Benz - E Class,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96251,202010225326060,90000.0,53,Silver,Mercedes-Benz,A Class,USED,2003.0,1295,Hatchback,False,Petrol,Mercedes-Benz - A Class,19
96254,202010235370666,15713.0,68,Grey,Mercedes-Benz,A Class,USED,2018.0,19900,Hatchback,False,Petrol,Mercedes-Benz - A Class,4
96260,202010285515611,50000.0,63,Black,Mercedes-Benz,E Class,USED,2014.0,11995,Estate,False,Diesel,Mercedes-Benz - E Class,8
96262,202010285527271,22153.0,18,Blue,Mercedes-Benz,C Class,USED,2018.0,20800,Saloon,False,Diesel,Mercedes-Benz - C Class,4
96264,202010295556637,28225.0,17,White,Mercedes-Benz,C Class,USED,2017.0,18499,Saloon,False,Diesel,Mercedes-Benz - C Class,5

In [5]:
b=csvv_df[csvv_df["standard_make"]=="Volkswagen"]
b

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
1,202010155026725,52023.0,66,Blue,Volkswagen,Golf,USED,2016.0,13500,Estate,False,Diesel,Volkswagen - Golf,6
7,202002137274498,35000.0,64,Black,Volkswagen,Golf,USED,2014.0,14500,Hatchback,False,Diesel,Volkswagen - Golf,8
9,202006260546963,64785.0,61,Silver,Volkswagen,Polo,USED,2011.0,4995,Hatchback,False,Diesel,Volkswagen - Polo,11
13,202008152524052,4290.0,20,Blue,Volkswagen,Golf,USED,2020.0,28190,Hatchback,False,Petrol,Volkswagen - Golf,2
14,202008192669061,121000.0,10,Black,Volkswagen,Golf,USED,2010.0,3995,Hatchback,False,Diesel,Volkswagen - Golf,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96220,202009274280181,115000.0,60,Blue,Volkswagen,Golf,USED,2010.0,3550,Hatchback,False,Diesel,Volkswagen - Golf,12
96224,202009304418482,69278.0,13,Silver,Volkswagen,Golf,USED,2013.0,7590,Hatchback,False,Diesel,Volkswagen - Golf,9
96229,202010074712714,14395.0,17,White,Volkswagen,Golf,USED,2017.0,13760,Hatchback,False,Diesel,Volkswagen - Golf,5
96247,202010205239879,83172.0,63,Grey,Volkswagen,Golf,USED,2013.0,7850,Hatchback,False,Diesel,Volkswagen - Golf,9
96253,202010235346303,17482.0,19,Grey,Volkswagen,Golf,USED,2019.0,16591,Hatchback,False,Petrol,Volkswagen - Golf,3

In [6]:
c=csvv_df[csvv_df["standard_make"]=="Vauxhall"]
c

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
3,202009183894045,35300.0,18,Grey,Vauxhall,Corsa,USED,2018.0,7293,Hatchback,False,Petrol,Vauxhall - Corsa,4
6,202010155027121,17020.0,17,Grey,Vauxhall,Corsa,USED,2017.0,6795,Hatchback,False,Petrol,Vauxhall - Corsa,5
8,202006150161276,61760.0,09,Silver,Vauxhall,Corsa,USED,2009.0,2295,Hatchback,False,Petrol,Vauxhall - Corsa,13
10,202006290651340,117420.0,61,Silver,Vauxhall,Astra,USED,2011.0,2295,Estate,False,Diesel,Vauxhall - Astra,11
12,202008112332443,17499.0,18,White,Vauxhall,Corsa,USED,2018.0,8499,Hatchback,False,Petrol,Vauxhall - Corsa,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96245,202010205228822,12584.0,19,Grey,Vauxhall,Corsa,USED,2019.0,9499,Hatchback,False,Petrol,Vauxhall - Corsa,3
96248,202010215279274,58000.0,10,Black,Vauxhall,Astra,USED,2010.0,4549,Hatchback,False,Petrol,Vauxhall - Astra,12
96258,202010265445023,108000.0,60,Silver,Vauxhall,Astra,USED,2011.0,2495,Hatchback,False,Petrol,Vauxhall - Astra,11
96263,202010285546060,44000.0,64,Silver,Vauxhall,Corsa,USED,2014.0,4250,Hatchback,False,Petrol,Vauxhall - Corsa,8
96266,202010315639231,45000.0,15,Silver,Vauxhall,Corsa,USED,2015.0,5000,Hatchback,False,Petrol,Vauxhall - Corsa,7

In [7]:
d=csvv_df[csvv_df["standard_make"]=="Nissan"]
d

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
4,202010014441671,47299.0,65,Black,Nissan,Qashqai,USED,2016.0,11500,SUV,False,Diesel,Nissan - Qashqai,6
20,202009073432201,30678.0,67,Black,Nissan,Qashqai,USED,2018.0,13550,SUV,False,Diesel,Nissan - Qashqai,4
31,202009234083878,22764.0,17,Blue,Nissan,Qashqai,USED,2017.0,11069,Hatchback,False,Diesel,Nissan - Qashqai,5
39,202009304410540,10000.0,68,Silver,Nissan,Qashqai,USED,2018.0,18495,SUV,False,Diesel,Nissan - Qashqai,4
44,202010064647216,10.0,70,White,Nissan,Qashqai,USED,2020.0,24995,SUV,False,Diesel,Nissan - Qashqai,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96243,202010195177111,7456.0,69,Blue,Nissan,Qashqai,USED,2020.0,16999,SUV,False,Petrol,Nissan - Qashqai,2
96249,202010225292123,44900.0,15,Black,Nissan,Qashqai,USED,2015.0,10685,SUV,False,Petrol,Nissan - Qashqai,7
96259,202010275480505,93000.0,61,Black,Nissan,Juke,USED,2011.0,4490,SUV,False,Petrol,Nissan - Juke,11
96267,202010315647416,4075.0,69,Grey,Nissan,Juke,USED,2019.0,18000,SUV,False,Petrol,Nissan - Juke,3
96268,202010315659271,52760.0,62,White,Nissan,Qashqai,USED,2012.0,7250,SUV,False,Petrol,Nissan - Qashqai,10

In [8]:
e=csvv_df[csvv_df["standard_make"]=="Audi"]
e

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
11,202007101093756,47000.0,16,Black,Audi,A1,USED,2016.0,9800,Hatchback,False,Petrol,Audi - A1,6
16,202008262959989,33000.0,66,Silver,Audi,A1,USED,2016.0,14995,Hatchback,False,Diesel,Audi - A1,6
49,202010074711401,33847.0,18,Black,Audi,A3,USED,2018.0,18075,Saloon,False,Petrol,Audi - A3,4
55,202010124894836,41227.0,15,Blue,Audi,A1,USED,2015.0,11799,Hatchback,False,Petrol,Audi - A1,7
60,202010165061794,63262.0,13,White,Audi,A1,USED,2013.0,9000,Hatchback,False,Diesel,Audi - A1,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96183,202010295558613,21604.0,18,White,Audi,A1,USED,2018.0,12300,Hatchback,False,Petrol,Audi - A1,4
96204,202008272977926,32874.0,16,White,Audi,A1,USED,2016.0,10980,Hatchback,False,Diesel,Audi - A1,6
96206,202009043316458,39894.0,66,Black,Audi,A3,USED,2017.0,11900,Hatchback,False,Diesel,Audi - A3,5
96212,202009224061193,21400.0,65,Grey,Audi,A3,USED,2015.0,14750,Hatchback,False,Petrol,Audi - A3,7
96237,202010144989694,6515.0,19,White,Audi,A1,USED,2019.0,20455,Hatchback,False,Petrol,Audi - A1,3

In [9]:
f=csvv_df[csvv_df["standard_make"]=="MINI"]
f

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
0,202010014440649,31534.0,17,Grey,MINI,Hatch,USED,2017.0,19000,Hatchback,False,Petrol,MINI - Hatch,5
23,202009133687405,52618.0,67,Grey,MINI,Hatch,USED,2017.0,10250,Hatchback,False,Petrol,MINI - Hatch,5
43,202010054613232,5937.0,17,Silver,MINI,Hatch,USED,2017.0,11980,Hatchback,False,Diesel,MINI - Hatch,5
80,202007091057229,11035.0,65,Black,MINI,Hatch,USED,2016.0,11995,Hatchback,False,Petrol,MINI - Hatch,6
101,202009153776857,40000.0,56,Black,MINI,Hatch,USED,2006.0,4800,Hatchback,False,Petrol,MINI - Hatch,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96133,202009244143795,7764.0,16,Blue,MINI,Hatch,USED,2016.0,12500,Hatchback,False,Petrol,MINI - Hatch,6
96147,202010054618935,12005.0,68,White,MINI,Hatch,USED,2018.0,12299,Hatchback,False,Petrol,MINI - Hatch,4
96154,202010074732961,46500.0,10,Black,MINI,Hatch,USED,2010.0,4499,Hatchback,False,Petrol,MINI - Hatch,12
96161,202010165094511,27000.0,16,Black,MINI,Hatch,USED,2016.0,8150,Hatchback,False,Diesel,MINI - Hatch,6
96221,202009294358595,10460.0,69,Silver,MINI,Hatch,USED,2020.0,17790,Hatchback,False,Petrol,MINI - Hatch,2

In [10]:
g=csvv_df[csvv_df["standard_make"]=="Kia"]
g

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
50,202010074726490,55520.0,64,White,Kia,Sportage,USED,2014.0,9900,SUV,False,Petrol,Kia - Sportage,8
58,202010155054549,33670.0,66,White,Kia,Sportage,USED,2016.0,10495,SUV,False,Diesel,Kia - Sportage,6
98,202009103546522,9582.0,19,Silver,Kia,Sportage,USED,2019.0,17995,SUV,False,Petrol,Kia - Sportage,3
104,202009224067937,34837.0,17,Black,Kia,Sportage,USED,2017.0,11200,SUV,False,Petrol,Kia - Sportage,5
109,202010024509255,67000.0,64,Silver,Kia,Sportage,USED,2014.0,8495,SUV,False,Diesel,Kia - Sportage,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96145,202010044587339,75094.0,67,White,Kia,Sportage,USED,2017.0,11495,SUV,False,Diesel,Kia - Sportage,5
96148,202010064648480,26321.0,19,Black,Kia,Sportage,USED,2019.0,21300,SUV,False,Diesel,Kia - Sportage,3
96156,202010104847418,19028.0,67,Grey,Kia,Sportage,USED,2018.0,14995,SUV,False,Petrol,Kia - Sportage,4
96172,202010235331457,43000.0,65,White,Kia,Sportage,USED,2016.0,15300,SUV,False,Diesel,Kia - Sportage,6
96200,202008072194972,21022.0,17,White,Kia,Sportage,USED,2017.0,11393,SUV,False,Diesel,Kia - Sportage,5

In [11]:
h=csvv_df[csvv_df["standard_make"]=="Renault"]
h

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
17,202008262968969,30228.0,16,White,Renault,Clio,USED,2016.0,11999,Hatchback,False,Petrol,Renault - Clio,6
29,202009224036334,84000.0,58,Black,Renault,Clio,USED,2008.0,1499,Hatchback,False,Petrol,Renault - Clio,14
40,202010024508937,9003.0,67,White,Renault,Clio,USED,2017.0,8595,Hatchback,False,Petrol,Renault - Clio,5
57,202010134958350,58472.0,63,Blue,Renault,Clio,USED,2013.0,5495,Hatchback,False,Petrol,Renault - Clio,9
68,202010245396323,86500.0,08,Black,Renault,Clio,USED,2008.0,1390,Hatchback,False,Petrol,Renault - Clio,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96137,202009304401157,49000.0,14,Blue,Renault,Clio,USED,2014.0,7490,Hatchback,False,Petrol,Renault - Clio,8
96159,202010134950296,43272.0,61,White,Renault,Clio,USED,2011.0,7495,Hatchback,False,Petrol,Renault - Clio,11
96175,202010235368048,89000.0,07,Blue,Renault,Clio,USED,2007.0,930,Hatchback,False,Petrol,Renault - Clio,15
96236,202010124924270,67000.0,62,White,Renault,Clio,USED,2012.0,8995,Hatchback,False,Petrol,Renault - Clio,10
96252,202010235340603,77000.0,07,Black,Renault,Clio,USED,2007.0,1995,Hatchback,False,Petrol,Renault - Clio,15

In [12]:
i=csvv_df[csvv_df["standard_make"]=="Fiat"]
i

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
25,202009173835338,32479.0,66,Blue,Fiat,500,USED,2016.0,6750,Hatchback,False,Petrol,Fiat - 500,6
151,202010285534251,43000.0,13,White,Fiat,500,USED,2013.0,4990,Hatchback,False,Petrol,Fiat - 500,9
158,202002287827835,30144.0,13,White,Fiat,500,USED,2013.0,4195,Hatchback,False,Petrol,Fiat - 500,9
203,202010094796657,67450.0,13,White,Fiat,500,USED,2013.0,3590,Hatchback,False,Petrol,Fiat - 500,9
223,202010245375344,34924.0,59,White,Fiat,500,USED,2009.0,3700,Hatchback,False,Petrol,Fiat - 500,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96169,202010215252316,35111.0,64,Blue,Fiat,500,USED,2014.0,5600,Hatchback,False,Petrol,Fiat - 500,8
96170,202010215256008,100000.0,59,Grey,Fiat,500,USED,2009.0,2250,Hatchback,False,Diesel,Fiat - 500,13
96210,202009183900694,45000.0,63,White,Fiat,500,USED,2013.0,5295,Hatchback,False,Petrol,Fiat - 500,9
96222,202009294365355,24000.0,65,Black,Fiat,500,USED,2015.0,6495,Hatchback,False,Petrol,Fiat - 500,7
96256,202010245401488,33356.0,17,White,Fiat,500,USED,2017.0,6495,Hatchback,False,Petrol,Fiat - 500,5

In [13]:
j=csvv_df[csvv_df["standard_make"]=="Toyota"]
j

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
5,202010235355785,7990.0,19,Black,Toyota,Yaris,USED,2019.0,11147,Hatchback,False,Petrol,Toyota - Yaris,3
72,202010285535376,6506.0,68,Blue,Toyota,Yaris,USED,2018.0,9845,Hatchback,False,Petrol,Toyota - Yaris,4
177,202009173855614,15250.0,68,Grey,Toyota,Yaris,USED,2018.0,9490,Hatchback,False,Petrol,Toyota - Yaris,4
379,202010265459337,8020.0,19,Grey,Toyota,Yaris,USED,2019.0,12495,Hatchback,False,Petrol,Toyota - Yaris,3
382,202010285525838,12023.0,66,Blue,Toyota,Yaris,USED,2017.0,8595,Hatchback,False,Petrol,Toyota - Yaris,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95824,202010155047604,2450.0,69,Grey,Toyota,Yaris,USED,2019.0,13900,Hatchback,False,Petrol,Toyota - Yaris,3
95877,202009214013367,11409.0,67,Black,Toyota,Yaris,USED,2017.0,9495,Hatchback,False,Petrol,Toyota - Yaris,5
96007,202010205233970,161000.0,10,Black,Toyota,Yaris,USED,2010.0,1150,Hatchback,False,Diesel,Toyota - Yaris,12
96166,202010195182595,3918.0,20,Grey,Toyota,Yaris,USED,2020.0,16990,Hatchback,False,Petrol,Toyota - Yaris,2
96189,202011015664903,120000.0,55,Silver,Toyota,Yaris,USED,2005.0,990,Hatchback,False,Petrol,Toyota - Yaris,17

In [14]:
k=csvv_df[csvv_df["standard_make"]=="BMW"]
k

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,make_model,age
19,202009033282749,14000.0,18,Black,BMW,5 Series,USED,2018.0,27990,Saloon,False,Diesel,BMW - 5 Series,4
21,202009093495711,25287.0,67,Silver,BMW,5 Series,USED,2017.0,20000,Saloon,False,Diesel,BMW - 5 Series,5
22,202009123632076,102498.0,15,Black,BMW,1 Series,USED,2015.0,6990,Hatchback,False,Diesel,BMW - 1 Series,7
28,202009183920571,62000.0,66,Blue,BMW,5 Series,USED,2016.0,17850,Saloon,False,Diesel,BMW - 5 Series,6
35,202009284293085,9066.0,69,Blue,BMW,5 Series,USED,2019.0,24495,Saloon,False,Petrol,BMW - 5 Series,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96250,202010225317647,29337.0,16,Blue,BMW,3 Series,USED,2016.0,15000,Estate,False,Diesel,BMW - 3 Series,6
96255,202010245397920,131980.0,08,Black,BMW,1 Series,USED,2008.0,3400,Hatchback,False,Diesel,BMW - 1 Series,14
96257,202010255424987,40000.0,62,Black,BMW,3 Series,USED,2012.0,10100,Coupe,False,Diesel,BMW - 3 Series,10
96261,202010285515718,100000.0,59,Silver,BMW,3 Series,USED,2010.0,4395,Saloon,False,Diesel,BMW - 3 Series,12
96265,202010305614799,122000.0,07,Silver,BMW,3 Series,USED,2007.0,1990,Saloon,False,Petrol,BMW - 3 Series,15

# Writing into Excel diffrent sheets

In [15]:
writer = pd.ExcelWriter("car_category_multiple_to_Excel.xlsx")
a.to_excel(writer, sheet_name= "sheet1")
b.to_excel(writer, sheet_name= "sheet2")
c.to_excel(writer, sheet_name= "sheet3")
d.to_excel(writer, sheet_name= "sheet4")
e.to_excel(writer, sheet_name= "sheet5")
f.to_excel(writer, sheet_name= "sheet6")
g.to_excel(writer, sheet_name= "sheet7")
h.to_excel(writer, sheet_name= "sheet8")
i.to_excel(writer, sheet_name= "sheet9")
j.to_excel(writer, sheet_name= "sheet10")
k.to_excel(writer, sheet_name= "sheet11")
writer.save()